# Generated by Django 4.2.13 on 2024-07-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
